### ISSUE TITLE
Реализовать регулярное выражение для фильтров 

### ISSUE THREAD

**Issue by annstgn** [egal/php-project#27]
**Задача**

Нужны 3 регулярки для строки query-параметра filter, содержащей фильтр запроса getItems:
1. Регулярка для полной строки фильтра
2. Регулярка для простого условия
3. Регулярка для сложного условия

**Формат строки query-параметра filter**

Формат простого условия:

>filed1 operator value1

Формат сложного условия:

> filed1 operator value1 and ((filed2 operator value2 or filed3 operator value3) or (filed4 operator value4))

Ограничения на значения:
1. filed - строка без пробелов в snake_case
4. operator - значение из списка ('eq', 'not eq', 'eqi', 'not eqi', 'gt', 'ge', 'lt', 'le', 'co', 'coi', 'not co', 'not coi', 'sw', 'swi', 'ew', 'ewi')
5. value1 - строка, integer, float, boolean
6. combiner - значение из списка ('and', 'or')

Возможные ошибки:
1. Недостает обязательного элемента
2. Лишние пробелы
3. Невалидное значение обязательного элемента

**Примеры валидных и невалидных строк**

> Передаваемая строка: 'field1 eq value1',
> Ошибка: нет,
> Массив соответствий по 1й регулярке:  
> ```
>   [
>       'field1 eq value1'
>   ]
> ```
> Массив соответствий по 2й регулярке для простого условия:  
> ```
>   [
>       '',
>       'field1',
>       'eq',
>       'value1'
>   ]
> ```

> Передаваемая строка: 'field1 eq value1 or (field2 co value and field3 ge value3)',
> Ошибка: нет,
> Массив соответствий по 1й регулярке:  
> ```
>   [
>       'field1 eq value1',
>       'or (field2 co value and field3 ge value3)'
>   ]
> ```
> Массив соответствий по 2й регулярке для сложного условия:  
> ```
>   [
>       'or',
>       'fifield2 co value',
>       'and field3 ge value3'
>   ]
> ```

> Передаваемая строка: '(field1 eq value1 and (field2 eq value2 or field3 eq value3)) or field4 equal value4',
> Ошибка: нет,
> Массив соответствий по 1й регулярке:  
> ```
>   [
>       '(field1 eq value1 and (field2 eq value2 or field3 eq value3))',
>       'or field4 equal value4'
>   ]
> ```
> Массив соответствий по 2й регулярке для сложного условия:  
> ```
>   [
>       '',
>       'field1 eq value1',
>       'and (field2 eq value2 or field3 eq value3)'
>   ]
> ```

> Передаваемая строка: 'relation.field1 eq value1 and field2 eq value2',
> Ошибка: нет,
> Массив соответствий по 1й регулярке:  
> ```
> [
>      'relation.field1 eq value1',
>      'and field2 eq value2'
>  ]
> ```

> Передаваемая строка: 'field1 eq',
> Ошибка: недостает обязательного элемента,
> Массив соответствий: нет

> Передаваемая строка: 'field1 eq value1 field2 eq value2',
> Ошибка: недостает обязательного элемента,
> Массив соответствий: нет

> Передаваемая строка:  'field1 eq value1 or field2 eq value2',
> Ошибка: нет,
> Массив соответствий:  
> ```
> [
>     'field1 eq value1',
>     'or field2 eq value2'
> ]
> ```

> Передаваемая строка: 'field1 eq   value1 or field2 eq value2',
> Ошибка: лишние пробелы,
> Массив соответствий: неть

> Передаваемая строка:  'field1 gt value1 or field2 eq value2',
> Ошибка: нет,
> Массив соответствий:  
> ```
> [
>     'field1 gt value1',
>     'or field2 eq value2'
> ]
> ```

> Передаваемая строка: 'field1 gt value1 AND field2 eq value2',
> Ошибка: невалидное значение обязательного элемента,
> Массив соответствий: нет

> Передаваемая строка: 'field1 gt value1 bla field2 eq value2',
> Ошибка: невалидное значение обязательного элемента,
> Массив соответствий: неть

**Comment by novkri** [comment]
1. Регулярка для полной строки фильтра (не доделана): `(?<parenthesis>(?<combiner_full>(?<combiner>and|or)\s){0,1}\((?:[^()]|(?<sub_parenthesis>(?&parenthesis)))+\))|(?(?=^)(?&combiner_full){0,1}(?<filter>(?<field>[A-Za-z0-9_.]+)\s(?<operator>eq|not eq|eqi|not eqi|gt|ge|lt|le|co|coi|not co|not coi|sw|swi|ew|ewi)\s(?<value>[A-Za-z0-9_.]+))|(?&combiner_full){1}(?&filter))`  
Работает некорректно при невалидных\отстутвующих значениях опреатора 

2. Регулярка для простого условия: `(?<filter>(?<field>[A-Za-z0-9_.]+)\s(?<operator>eq|not eq|eqi|not eqi|gt|ge|lt|le|co|coi|not co|not coi|sw|swi|ew|ewi)\s(?<value>[A-Za-z0-9_.]+))`
3. Регулярка для сложного условия (?): `(?<parenthesis>(?<combiner_full>(?<combiner>and|or)\s){0,1}\((?:[^()]|(?<sub_parenthesis>(?&parenthesis)))+\))|(?<filter>(?<field>[A-Za-z0-9_.]+)\s(?<operator>eq|not eq|eqi|not eqi|gt|ge|lt|le|co|coi|not co|not coi|sw|swi|ew|ewi)\s(?<value>[A-Za-z0-9_.]+))`

как вариант
