### ISSUE TITLE
Презентация концепции

### ISSUE THREAD

**Issue by annstgn** [egal/php-project#6]

**Comment by LinnDevon** [comment]
https://docs.google.com/document/d/1z6cnJDuSdP8-WzYuxMll7R_LSFZTRj4lUkB3w9kHULk/edit?usp=sharing

**Comment by annstgn** [comment]
@LinnDevon  :triangular_flag_on_post: 2 составление текста презентации

**Comment by LinnDevon** [comment]
@annstgn :triangular_flag_on_post: 2 за составление текста презентации
@annstgn :triangular_flag_on_post: 2 за реализацию концепции новой версии Egal
